Sound Feature added to Java Chess Game
cagdasgerede/JavaChess pull request #10
Opened 2020-12-15 20:51 UTC by talhaunal99

2020-12-15 21:01 UTC, talhaunal99 commented
https://youtu.be/jlh2aiG2QfI Here is my video link.

2020-12-19 12:59 UTC, cagdasgerede commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Bu senin development environment icin olan bir dosya. Bu dosya adini .gitignore dosyasina ekle ve bu dosyayi PRdan cikart.

2020-12-19 13:00 UTC, cagdasgerede commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Bu dosya icin de yukarida soylediklerim gecerli.

2020-12-19 13:00 UTC, cagdasgerede commented on .settings/org.eclipse.buildship.core.prefs
> +arguments=
Bu dosya icin de yukarida soylediklerim gecerli.

2020-12-19 13:00 UTC, cagdasgerede commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
Bu dosya icin de yukarida soylediklerim gecerli.

2020-12-19 13:03 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/BoardPoint.java
> +import pl.nogacz.chess.application.menu.SoundEffect;
Gereksiz import

2020-12-19 13:03 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/BoardPoint.java
> +}
missing newline

2020-12-19 13:04 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/ChessNotation.java
> +    SoundEffect sound= new SoundEffect("./src/main/resources/Audio/piece.wav");
Bu ses dosyalarını nereden aldın? Kaynağını burada belirt. copyright free efektler/müzikler kullanmaya dikkar et.

2020-12-19 13:05 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Computer.java
> +    SoundEffect sound,sound2;
fix spacing

````sound, sound2````

xxx1, xxx2, xxx3 gibi isimler kullanma lütfen. Daha manalı isimler seç.

2020-12-19 13:05 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Computer.java
> +    public static BoardPoint boardPoint = new BoardPoint();
public yapma, accessor metot yaz.

2020-12-19 13:06 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Computer.java
> +        sound= new SoundEffect("./src/main/resources/Audio/click.wav");
fix spacing

```sound = SoundEffect```

2020-12-19 13:11 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Computer.java
> +           // sound2.play(false); // Sound for piece loss
sil

2020-12-19 13:11 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Computer.java
> +           // sound2.play(false); // Sound for piece loss
sil

2020-12-19 13:12 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Computer.java
> +            sound2.play(false); // Sound for piece loss
Genel olarak ses yönetimini yeni bir classa al. O classın metotlarının isimleri intentionı direk yansıtsın. Mesela playPieceLossSound() gibi bir metot çağırabilirsin buradan.

2020-12-19 13:12 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Computer.java
> +        if(possibleKickAndNotIsEnemyKickMe.size() > 0) {
gereksiz değişiklik.

2020-12-19 13:13 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Design.java
> +import pl.nogacz.chess.application.menu.SoundEffect;
import sırası yanlış. Alfabetik olarak doğru yere koy.

2020-12-19 13:14 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Design.java
> +    SoundEffect sound= new SoundEffect("./src/main/resources/Audio/click.wav");
private static final CLICK_SOUND = new SoundEffect("./src/main/resources/Audio/click.wav");

2020-12-19 13:14 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Design.java
> +    public static SoundEffect menu_music= new SoundEffect("./src/main/resources/Audio/menu.wav");
private static final MENU_MUSIC = new SoundEffect("./src/main/resources/Audio/menu.wav");

2020-12-19 13:15 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Design.java
> +    public static SoundEffect background_music= new SoundEffect("./src/main/resources/Audio/background.wav");
private final static SoundEffect BACKGROUND_MUSIC = new SoundEffect("./src/main/resources/Audio/background.wav");

2020-12-19 13:16 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Design.java
> +        menu_music.play(true);
Yeni bir class al demistim yukarida. O classta soyle bir metot yazip buradan cagirabilirsin:

```
SoundManager.playMenuMusic()
```

2020-12-19 13:16 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/Design.java
> +
gereksiz degisiklik

2020-12-19 13:19 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/AuthorInfo.java
> +}
missing newline

2020-12-19 13:19 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/AuthorInfo.java
> +        sound.play(false); //Sound for Author button
SoundManager.playClickEffect()

2020-12-19 13:20 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/AuthorInfo.java
> +        sound = new SoundEffect("./src/main/resources/Audio/click.wav");
Bu detay yeni yazacagin SoundManager classina gitmeli

2020-12-19 13:21 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Difficulty.java
> +            sound.play(false); //Sound for Easy button
Ayni kod tekrar ediyor. play'i if disina alabilirsin. Cunku her ihtimalde cagiriliyor.

Ayrica su sekilde degistir burayi

SoundManager.playClickEffect()

2020-12-19 13:24 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Difficulty.java
> +        sound.play(false); //Sound for Difficulty button
SoundManager.playClickEffect()

2020-12-19 13:27 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Difficulty.java
> +        SoundEffect sound = new SoundEffect("./src/main/resources/Audio/click.wav");
Bu detay SoundManager'da olmali

2020-12-19 13:27 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/EndGame.java
> +        sound.play(false); //Sound for New Game button.
SoundManager.playClickEffect()

2020-12-19 13:27 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/EndGame.java
> +}
missing newline

2020-12-19 13:28 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/SoundEffect.java
> +import java.io.*;
```java.io.*``` kullanma. Kullandiklarini tek tek sirala

2020-12-19 13:29 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/SoundEffect.java
> +import javax.sound.sampled.*;
```javax.sound.sampled``` kullanma. Kullandiklarini tek tek sirala

2020-12-19 13:29 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/SoundEffect.java
> +	public class SoundEffect {
Indentation bozuk. Class tanimini en sola daya.

2020-12-19 13:30 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/SoundEffect.java
> +	         e.printStackTrace();
Buradaki catch blocklarindaki exceptionlari Log dosyasina logla. printStackTrace yapma.

2020-12-19 13:31 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/SoundEffect.java
> +	}
missing newline

2020-12-19 13:31 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/SoundEffect.java
> +	   public void stop() //Stop playing and rewind to be played again from the beginning
Parentezi yukari tasi

```public void stop() {```

2020-12-19 13:31 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Statistics.java
> +
gereksiz newline

2020-12-19 13:31 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Statistics.java
> +        sound.play(false); //Sound for statistics button
gereksiz comment.

SoundManager.playClickEffect();

2020-12-19 13:32 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Statistics.java
> +            sound.play(false); //Sound for Reset button in Statistics
SoundManager.playClickEffect();

2020-12-19 13:32 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Statistics.java
> +        sound.play(false); //Sound for OK button in Statistics
SoundManager.playClickEffect()

2020-12-19 13:32 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/application/menu/Statistics.java
> +}
missing newline

2020-12-19 13:33 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +import pl.nogacz.chess.application.menu.SoundEffect;
order yanlis. Once Computer sonra SoundEffect

2020-12-19 13:34 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +    static int moveNumber=0; //If moveNumber == 1, it means that it is the first move.
fix spacing

```moveNumber = 0```

2020-12-19 13:35 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +        sound= new SoundEffect("./src/main/resources/Audio/click.wav"); //SoundEffect object for Clicking
Bunlari SoundManager'a tasi

2020-12-19 13:35 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +        board.put(new Coordinates(3,0), new PawnClass(Pawn.QUEEN, PawnColor.BLACK)); //Bugfix: Wrong queen and king positions changed.
Comment gereksiz. Sil.

2020-12-19 13:37 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                Design.background_music.stop(); //Stops the background music
gereksiz comment.

Ayrica 

Bu iki satiri soyle bir metot cagirisi ile degistir:

```SoundManager.playVictorySound()```

O metotun icerisinde background_music.stop(); yapabilirsin.

2020-12-19 13:37 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                Design.background_music.stop(); //Stops the background music
Yukarida yazdigim gibi burada da ayni durum gecerli

2020-12-19 13:38 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                        sound4.play(false); //Sound for won piece.
SoundManager.playXXX()

2020-12-19 13:38 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                    Thread.sleep(2000); //Changed 1000 to 2000 because of the sound bug, it is not necessary but it works perfect with 2 seconds delay
Sound bug dedigin nedir? Ne oluyor tam olarak 1 saniye olunca?

2020-12-19 13:39 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                        Design.background_music.stop(); //Stops the background music
Yukaridakilere benzer duzeltme gerekiyor

2020-12-19 13:39 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                Design.background_music.stop(); //Stops the background music
Benzer duzeltme

2020-12-19 13:39 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                lightSelect(selectedCoordinates);
gereksiz degisiklik. Satir sonu bosluklari sil

2020-12-19 13:39 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                          Design.background_music.stop(); //Stops the background music
Bu iki satiri yukarilarda bahsettigim gibi duzelt.

2020-12-19 13:40 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +    public static boolean isFieldNotNull(Coordinates coordinates) {
gereksiz satir sonu bosluk

2020-12-19 13:40 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +            Design.menu_music.stop(); //Stops the background music
Duzelt yukarida anlattigim gibi

2020-12-19 13:40 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +            //sound4.play(false); //Sound for win a piece
Bu if bloguna ihtiyacin yok herhalde. Sil.

2020-12-19 13:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +
gereksiz newline

2020-12-19 13:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/chess/board/Board.java
> +            Design.addCheckedPawn(coordinates, pawn);
gereksiz satir sonu bosluk

2020-12-19 13:42 UTC, talhaunal99 commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                    Thread.sleep(2000); //Changed 1000 to 2000 because of the sound bug, it is not necessary but it works perfect with 2 seconds delay
Bazen ses efektleri duyulmayabiliyor hocam 1 saniye olduğunda. 2 saniyeye çıkardığımda her bir hamlede ve taş yenilmesinde ses efektleri eksiksiz duyuluyor.

2020-12-19 13:46 UTC, cagdasgerede requested changes
Kodda biraktigim notlara gore kodunu guncelle.

bin/ klasörü altında eklediklerini PRdan çıkart. Bu klasörü .gitignore'a ekle. bin klasörü derleme sonucu ortaya çıkan dosyaları içerdiği için repoda bulunmaması gerekir. Audio dosyalarını zaten resources altında PRa eklemişsin. Tekrar bin altındaki dosyalara gerek yok.

SoundManager gibi bir class yarat ve tum sesleri oraya tasi.

Yaptigin degisiklikler icin manali unit testler yaz.


Son olarak review e hazir oldugunda bana assign etmeyi unutma.

2020-12-19 18:07 UTC, talhaunal99 commented on src/main/java/pl/nogacz/chess/board/Board.java
> +                    Thread.sleep(2000); //Changed 1000 to 2000 because of the sound bug, it is not necessary but it works perfect with 2 seconds delay
Eklediğim ses dosyalarının süresini kısalttım, sorun çözüldü. Bu değişikliği geri aldım.

2021-03-22 23:57 UTC, closed without merging